version: '3'

services:

  elasticsearch:
    container_name: django_elasticsearch_dsl_drf_elasticsearch_es_7_12
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile-ES-7-12
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    volumes:
    - esdata712:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - cluster.routing.allocation.disk.watermark.low=97%
    - cluster.routing.allocation.disk.watermark.high=98%
    - cluster.routing.allocation.disk.watermark.flood_stage=99%
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  esdata712:
